// Generated by gencpp from file aer1217_ardrone_simulator/ToggleCam.msg
// DO NOT EDIT!


#ifndef AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAM_H
#define AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAM_H

#include <ros/service_traits.h>


#include <aer1217_ardrone_simulator/ToggleCamRequest.h>
#include <aer1217_ardrone_simulator/ToggleCamResponse.h>


namespace aer1217_ardrone_simulator
{

struct ToggleCam
{

typedef ToggleCamRequest Request;
typedef ToggleCamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleCam
} // namespace aer1217_ardrone_simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aer1217_ardrone_simulator::ToggleCam > {
  static const char* value()
  {
    return "8fc5f5608d6072d9e82dd30f42a4228c";
  }

  static const char* value(const ::aer1217_ardrone_simulator::ToggleCam&) { return value(); }
};

template<>
struct DataType< ::aer1217_ardrone_simulator::ToggleCam > {
  static const char* value()
  {
    return "aer1217_ardrone_simulator/ToggleCam";
  }

  static const char* value(const ::aer1217_ardrone_simulator::ToggleCam&) { return value(); }
};


// service_traits::MD5Sum< ::aer1217_ardrone_simulator::ToggleCamRequest> should match 
// service_traits::MD5Sum< ::aer1217_ardrone_simulator::ToggleCam > 
template<>
struct MD5Sum< ::aer1217_ardrone_simulator::ToggleCamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aer1217_ardrone_simulator::ToggleCam >::value();
  }
  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aer1217_ardrone_simulator::ToggleCamRequest> should match 
// service_traits::DataType< ::aer1217_ardrone_simulator::ToggleCam > 
template<>
struct DataType< ::aer1217_ardrone_simulator::ToggleCamRequest>
{
  static const char* value()
  {
    return DataType< ::aer1217_ardrone_simulator::ToggleCam >::value();
  }
  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aer1217_ardrone_simulator::ToggleCamResponse> should match 
// service_traits::MD5Sum< ::aer1217_ardrone_simulator::ToggleCam > 
template<>
struct MD5Sum< ::aer1217_ardrone_simulator::ToggleCamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aer1217_ardrone_simulator::ToggleCam >::value();
  }
  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aer1217_ardrone_simulator::ToggleCamResponse> should match 
// service_traits::DataType< ::aer1217_ardrone_simulator::ToggleCam > 
template<>
struct DataType< ::aer1217_ardrone_simulator::ToggleCamResponse>
{
  static const char* value()
  {
    return DataType< ::aer1217_ardrone_simulator::ToggleCam >::value();
  }
  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAM_H
