// Generated by gencpp from file aer1217_ardrone_simulator/ToggleCamRequest.msg
// DO NOT EDIT!


#ifndef AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAMREQUEST_H
#define AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aer1217_ardrone_simulator
{
template <class ContainerAllocator>
struct ToggleCamRequest_
{
  typedef ToggleCamRequest_<ContainerAllocator> Type;

  ToggleCamRequest_()
    {
    }
  ToggleCamRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleCamRequest_

typedef ::aer1217_ardrone_simulator::ToggleCamRequest_<std::allocator<void> > ToggleCamRequest;

typedef boost::shared_ptr< ::aer1217_ardrone_simulator::ToggleCamRequest > ToggleCamRequestPtr;
typedef boost::shared_ptr< ::aer1217_ardrone_simulator::ToggleCamRequest const> ToggleCamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aer1217_ardrone_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'aer1217_ardrone_simulator': ['/home/charlie/aer1217/labs/src/aer1217_ardrone_simulator/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aer1217_ardrone_simulator/ToggleCamRequest";
  }

  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleCamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aer1217_ardrone_simulator::ToggleCamRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AER1217_ARDRONE_SIMULATOR_MESSAGE_TOGGLECAMREQUEST_H
